import type { SiteContent } from '../types';

const event = {
  couple: {
    firstName: 'Lisette',
    secondName: 'Bjarty',
    displayName: 'Lisette & Bjarty',
    monogram: 'L & B',
  },
  date: {
    iso: '2027-05-22',
    display: '22 mei 2027',
  },
  timeZone: 'Europe/Amsterdam',
  place: 'Lage Vuursche',
  venue: {
    roomName: 'De Stal',
    organisationName: 'Restaurant De Lage Vuursche',
    address: 'Dorpsstraat 2, 3749 AD Lage Vuursche',
    mapsUrl: 'https://www.google.com/maps/place//data=!4m2!3m1!1s0x47c66a38fbf1566d:0x82db93feae7284e7?sa=X&ved=1t:8290&ictx=111',
  },
  rsvpDeadline: {
    iso: '2027-04-10',
    display: '10 april 2027',
  },
} satisfies SiteContent['event'];

export const siteContent = {
  metadata: {
    language: 'nl',
    title: `${event.couple.displayName} | ${event.date.display}`,
  },
  event,
  contacts: {
    generalEmail: 'hallo@lisetteenbjarty.nl',
    rsvpEmail: 'rsvp@lisetteenbjarty.nl',
    giftsEmail: 'cadeau@lisetteenbjarty.nl',
  },
  navigation: {
    monogram: event.couple.monogram,
    items: [
      { id: 'schedule', label: 'Programma', href: '#schedule' },
      { id: 'dresscode', label: 'Dresscode', href: '#dresscode' },
      { id: 'location', label: 'Praktisch', href: '#location' },
      { id: 'rsvp', label: 'RSVP', href: '#rsvp' },
    ],
    ctaLabel: 'RSVP',
    ctaHref: '#rsvp',
  },
  hero: {
    eyebrow: 'Wij gaan trouwen',
    firstName: event.couple.firstName,
    secondName: event.couple.secondName,
    dateLine: `${event.date.display} • ${event.place}`,
    scrollLabel: 'Ontdek onze dag',
  },
  story: {
    enabled: false,
    sectionId: 'story',
    heading: 'Ons verhaal',
    introduction: 'Binnenkort delen we hier meer over ons verhaal.',
    items: [],
    endingHeading: 'En het mooiste',
    endingText: 'moet nog komen.',
  },
  schedule: {
    sectionId: 'schedule',
    heading: 'Programma',
    dateLine: `Zaterdag ${event.date.display}`,
    events: [
      {
        id: 'ontvangst',
        time: '14.30 – 15.00',
        title: 'Ontvangst gasten',
        location: event.venue.roomName,
        icon: 'clock',
        description: 'We heten jullie van harte welkom bij De Stal.',
      },
      {
        id: 'ceremonie',
        time: '15.00 – 16.00',
        title: 'Ceremonie',
        location: event.venue.roomName,
        icon: 'heart',
        description: 'We geven elkaar het jawoord.',
      },
      {
        id: 'toost-en-taart',
        time: '16.00 – 17.00',
        title: 'Toost en taart',
        location: event.venue.roomName,
        icon: 'cake',
        description: 'Na de ceremonie proosten we samen en snijden we de taart aan.',
      },
      {
        id: 'diner',
        time: '17.00 – 20.00',
        title: 'Diner',
        location: event.venue.roomName,
        icon: 'utensils',
        description: 'We gaan met de daggasten aan tafel.',
      },
      {
        id: 'inloop-avondgasten',
        time: '20.00 – 20.30',
        title: 'Inloop avondgasten',
        location: event.venue.roomName,
        icon: 'users',
        description: 'We verwelkomen de avondgasten voor het feest.',
      },
      {
        id: 'feest',
        time: '20.30 – 00.00',
        title: 'Feest',
        location: event.venue.roomName,
        icon: 'music',
        description: 'We sluiten onze trouwdag samen af op de dansvloer.',
      },
    ],
  },
  dressCode: {
    sectionId: 'dresscode',
    eyebrow: 'Feestelijk & kleurrijk',
    heading: 'Dresscode',
    introduction: 'Kies een feestelijke outfit in blauw, turquoise, groen, geel, roze, paars, bruin, grijs, zwart, goud of zilver. Ga vooral voor een kleur waarin jij je mooi voelt.',
    inspirationLabel: 'Outfitinspiratie',
    inspiration: [
      {
        id: 'blauw',
        image: '/images/dresscode/blauw.webp',
        alt: 'Drie fictieve gasten in een marineblauw pak, een turquoise jurk en een hemelsblauw pak.',
      },
      {
        id: 'groen-geel-roze',
        image: '/images/dresscode/groen-geel-roze.webp',
        alt: 'Drie fictieve gasten in een smaragdgroen pak en jurken in geel en roze.',
      },
      {
        id: 'paars-bruin-grijs',
        image: '/images/dresscode/paars-bruin-grijs.webp',
        alt: 'Drie fictieve gasten in paarse en bruine pakken en een grijze jurk.',
      },
      {
        id: 'zwart-goud-zilver',
        image: '/images/dresscode/zwart-goud-zilver.webp',
        alt: 'Drie fictieve gasten in een zwart pak en jurken in goud en zilver.',
      },
    ],
    colorsLabel: 'Kleuren om uit te kiezen',
    colors: [
      { id: 'marineblauw', label: 'Marineblauw', color: '#1E3A5F', foreground: 'light' },
      { id: 'hemelsblauw', label: 'Hemelsblauw', color: '#5DADE2', foreground: 'dark' },
      { id: 'turquoise', label: 'Turquoise', color: '#0F766E', foreground: 'light' },
      { id: 'smaragdgroen', label: 'Smaragdgroen', color: '#047857', foreground: 'light' },
      { id: 'geel', label: 'Geel', color: '#EAB308', foreground: 'dark' },
      { id: 'roze', label: 'Roze', color: '#DB2777', foreground: 'light' },
      { id: 'paars', label: 'Paars', color: '#7E22CE', foreground: 'light' },
      { id: 'bruin', label: 'Bruin', color: '#7C4A2D', foreground: 'light' },
      { id: 'grijs', label: 'Grijs', color: '#6B7280', foreground: 'light' },
      { id: 'zwart', label: 'Zwart', color: '#1C1917', foreground: 'light' },
      { id: 'goud', label: 'Goud', color: '#CA8A04', foreground: 'dark' },
      { id: 'zilver', label: 'Zilver', color: '#CBD5E1', foreground: 'dark' },
    ],
    printNote: 'Een feestelijke print binnen dit kleurenpalet is ook van harte welkom.',
  },
  location: {
    sectionId: 'location',
    venueName: event.venue.roomName,
    venueContext: event.venue.organisationName,
    address: event.venue.address,
    mapHref: event.venue.mapsUrl,
    mapLabel: 'Open in Google Maps',
    heading: 'Praktische informatie',
    introduction: `Onze hele bruiloft vindt plaats bij ${event.venue.roomName} van ${event.venue.organisationName} in ${event.place}.`,
    travelOptions: [
      {
        id: 'auto',
        title: 'Met de auto',
        description: 'De locatie is het gemakkelijkst bereikbaar met de auto.',
        icon: 'car',
      },
      {
        id: 'parkeren',
        title: 'Gratis parkeren',
        description: 'Je kunt gratis parkeren op het parkeerterrein tegenover en achter het restaurant.',
        icon: 'parking',
      },
      {
        id: 'overnachten',
        title: 'Overnachten',
        description: 'Hotel Ernst Sillem Hoeve ligt iets verderop en is bereikbaar met de auto of taxi. Omdat het aantal kamers in de directe omgeving beperkt is, raden we aan om tijdig en rechtstreeks bij de accommodatie te reserveren.',
        icon: 'bed',
      },
      {
        id: 'terugreis',
        title: 'Veilig naar huis',
        description: 'Regel voor de terugreis bij voorkeur vooraf een taxi en rijd uiteraard niet met alcohol op.',
        icon: 'taxi',
      },
    ],
  },
  honeymoon: {
    enabled: false,
    sectionId: 'honeymoon',
    eyebrow: 'Onze reis',
    headingLineOne: 'Samen op',
    headingLineTwo: 'avontuur',
    quote: 'Binnenkort delen we hier meer over onze reis.',
    startDate: 'Meer informatie volgt',
    stops: [],
  },
  rsvp: {
    sectionId: 'rsvp',
    headingPrefix: 'Ben je',
    headingEmphasis: 'erbij?',
    deadline: `Laat ons uiterlijk ${event.rsvpDeadline.display} weten of je erbij bent.`,
    statusHeading: 'RSVP opent binnenkort',
    statusMessage: 'We werken aan een veilig formulier waarmee je reactie direct wordt opgeslagen. Zodra het klaar is, kun je hier reageren.',
    contactLabel: 'Vraag over RSVP',
    form: {
      invitationHeading: 'Deze uitnodiging is voor',
      wrongNamesMessage: 'Kloppen de namen niet? Mail ons dan even.',
      attendanceQuestionPrefix: 'Is',
      attendanceYesLabel: 'Ja, gezellig',
      attendanceNoLabel: 'Nee, helaas',
      mealQuestionPrefix: 'Kies een maaltijd voor',
      mealChoices: {
        fish: 'Vis',
        meat: 'Vlees',
        vegetarian: 'Vega',
        vegan: 'Vegan',
      },
      emailLabel: 'E-mailadres (optioneel)',
      emailHelper: 'Als je je e-mailadres invult, kunnen we je via dit adres op de hoogte houden van praktische informatie over de bruiloft.',
      emailConfirmationNote: 'Je ontvangt nog geen automatische bevestigingsmail; bewaar na het opslaan je ontvangstnummer.',
      messageLabel: 'Bericht voor ons (optioneel)',
      messageHelper: 'Wil je nog iets aan ons kwijt? Deel hier alleen informatie die nodig is voor onze bruiloft.',
      submitLabel: 'Reactie versturen',
      updateLabel: 'Wijzigingen opslaan',
      privacyHeading: 'Wat we met je gegevens doen',
      privacyMessage: 'We gebruiken je naam, aanwezigheid, maaltijdkeuze, e-mailadres en eventuele bericht alleen om onze bruiloft te organiseren. Alleen Lisette, Bjarty en de mensen die onze RSVP beheren kunnen deze gegevens bekijken. We verwijderen de RSVP-gegevens uiterlijk 1 augustus 2027. Heb je een vraag over je gegevens of wil je ze inzien of corrigeren? Mail rsvp@lisetteenbjarty.nl.',
    },
    states: {
      loading: 'We halen jullie uitnodiging op…',
      invalidLink: 'Deze persoonlijke link is niet geldig of niet meer actief. Controleer of je de volledige link hebt geopend.',
      loadError: 'We kunnen je uitnodiging nu niet ophalen. Probeer het opnieuw; er is niets gewijzigd.',
      offline: 'Je bent offline. Je invoer blijft op dit scherm staan. Maak opnieuw verbinding en probeer het daarna opnieuw.',
      submitting: 'Je reactie wordt veilig opgeslagen…',
      validationError: 'Controleer de gemarkeerde antwoorden.',
      submitError: 'Opslaan is niet gelukt. Je invoer staat nog klaar. Probeer het opnieuw.',
      conflict: 'Er is via deze persoonlijke link intussen een nieuwere reactie opgeslagen. Laad eerst die reactie en voer je wijziging daarna opnieuw in; zo overschrijven we niets ongemerkt.',
      rateLimited: 'Er zijn te veel pogingen gedaan. Wacht even en probeer het daarna opnieuw. Je invoer blijft staan.',
      closed: 'De RSVP is gesloten. Wil je nog iets wijzigen? Mail rsvp@lisetteenbjarty.nl.',
      success: 'Je reactie is opgeslagen.',
      receiptLabel: 'Ontvangstnummer',
      receiptHelper: `Bewaar dit nummer. Via je persoonlijke link kun je je reactie tot ${event.rsvpDeadline.display} aanpassen.`,
      retryLabel: 'Opnieuw proberen',
      loadLatestLabel: 'Laatste opgeslagen reactie bekijken',
    },
  },
  footer: {
    coupleLabel: event.couple.displayName,
    contactLabel: 'Contact',
    copyright: `© 2027 ${event.couple.displayName}`,
    credit: 'Met liefde gemaakt',
    links: [],
  },
} satisfies SiteContent;
