import type { SiteContent } from '../types';

export const siteContent = {
  metadata: {
    language: 'en',
    title: 'Time for a wedding - 22 May 2027',
  },
  navigation: {
    monogram: 'A & B',
    items: [
      { id: 'story', label: 'Story', href: '#story' },
      { id: 'schedule', label: 'Schedule', href: '#schedule' },
      { id: 'location', label: 'Location', href: '#location' },
      { id: 'honeymoon', label: 'Honeymoon', href: '#honeymoon' },
      { id: 'rsvp', label: 'RSVP', href: '#rsvp' },
    ],
    ctaLabel: 'RSVP Now',
    ctaHref: '#rsvp',
  },
  hero: {
    eyebrow: 'To have and to hold',
    firstName: 'Arthur',
    secondName: 'Beatrice',
    dateLine: 'September 12th, 2026 • Florence, Italy',
    scrollLabel: 'Scroll to Explore',
  },
  story: {
    sectionId: 'story',
    heading: 'Our Story',
    introduction: 'A journey of thousand miles began with a single chapter. Swipe or scroll to see how we found our way to each other.',
    items: [
      {
        id: 'first-encounter',
        year: '2019',
        title: 'The First Encounter',
        text: 'A chance meeting at a small bookstore in London. It started with a debate over a rare edition of Dickens and ended with coffee that lasted until closing time.',
        image: 'https://images.unsplash.com/photo-1516972810927-80185027ca84?auto=format&fit=crop&q=80&w=1000',
      },
      {
        id: 'first-journey',
        year: '2021',
        title: 'The First Journey',
        text: 'Our first trip together to the coast of Cornwall. Lost in the mist, we found a shared love for the wild landscapes and stormy seas.',
        image: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&q=80&w=1000',
      },
      {
        id: 'proposal',
        year: '2023',
        title: 'The Proposal',
        text: 'Under the starlit sky of the Scottish Highlands. No fancy dinner, just a campfire, a quiet promise, and a ring that felt like home.',
        image: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&q=80&w=1000',
      },
      {
        id: 'building-our-nest',
        year: '2024',
        title: 'Building Our Nest',
        text: "A year of painting walls, choosing curtains, and realizing that home isn't a place, but a person. We started our life together officially.",
        image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=1000',
      },
    ],
    endingHeading: 'And the best is...',
    endingText: 'Yet to come.',
  },
  schedule: {
    sectionId: 'schedule',
    heading: 'The Celebration',
    dateLine: 'Saturday, September 12th',
    events: [
      {
        id: 'ceremony',
        time: '14:30',
        title: 'The Ceremony',
        location: 'Villa La Vedetta Terrace',
        icon: 'sparkles',
        description: 'A sunset vow exchange overlooking the Duomo.',
      },
      {
        id: 'cocktail-hour',
        time: '16:00',
        title: 'Cocktail Hour',
        location: 'The Rose Garden',
        icon: 'utensils',
        description: 'Italian Apertivo with classical strings quartet.',
      },
      {
        id: 'wedding-banquet',
        time: '18:30',
        title: 'Wedding Banquet',
        location: 'The Grand Hall',
        icon: 'utensils',
        description: 'A five-course Tuscan culinary journey.',
      },
      {
        id: 'first-dance',
        time: '21:00',
        title: 'First Dance & Party',
        location: 'The Glass Pavilion',
        icon: 'music',
        description: 'Dancing under the stars to our favorite vinyls.',
      },
    ],
  },
  location: {
    sectionId: 'location',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1000',
    imageAlt: 'Florence Italy',
    venueName: 'Villa La Vedetta',
    address: 'Viale Michelangiolo, 70, Florence',
    heading: 'Getting There',
    introduction: "Florence is most magical when approached with patience. Whether flying into Peretola or arriving by train through the Tuscan hills, we can't wait to see you.",
    travelOptions: [
      {
        id: 'air',
        title: 'By Air',
        description: 'Florence Airport (FLR) is 20mins away. Pisa Airport (PSA) is 1hr by shuttle.',
        icon: 'plane',
        variant: 'default',
      },
      {
        id: 'rail',
        title: 'By Rail',
        description: 'Santa Maria Novella Station connects to all major Italian cities.',
        icon: 'train',
        variant: 'default',
      },
      {
        id: 'parking',
        title: 'Parking',
        description: 'Valet parking is available at the villa for all guests throughout the event.',
        icon: 'car',
        variant: 'default',
      },
      {
        id: 'maps',
        title: 'Open in Maps',
        description: 'Get turn-by-turn directions directly to our celebration.',
        icon: 'map',
        variant: 'maps',
      },
    ],
  },
  honeymoon: {
    sectionId: 'honeymoon',
    eyebrow: 'The Odyssey',
    headingLineOne: 'Follow Our',
    headingLineTwo: 'Honeymoon',
    quote: '"Not all those who wander are lost."',
    startDate: 'Starting September 20th, 2026',
    stops: [
      {
        id: 'tokyo',
        day: 1,
        location: 'Tokyo, Japan',
        title: 'Neon Dreams',
        icon: 'sun',
        image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&q=80&w=1000',
        description: 'Exploring the juxtaposition of tradition and technology in the heart of Japan. From hidden shrines to neon-lit streets.',
      },
      {
        id: 'kyoto',
        day: 4,
        location: 'Kyoto',
        title: 'Ancient Echoes',
        icon: 'wind',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=1000',
        description: 'Exploring the juxtaposition of tradition and technology in the heart of Japan. From hidden shrines to neon-lit streets.',
      },
      {
        id: 'mount-fuji',
        day: 8,
        location: 'Mount Fuji',
        title: 'The Silent Peak',
        icon: 'camera',
        image: 'https://images.unsplash.com/photo-1509023464722-18d996393ca8?auto=format&fit=crop&q=80&w=1000',
        description: 'Exploring the juxtaposition of tradition and technology in the heart of Japan. From hidden shrines to neon-lit streets.',
      },
      {
        id: 'okinawa',
        day: 12,
        location: 'Okinawa',
        title: 'Soul of the Sea',
        icon: 'map-pin',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=1000',
        description: 'Exploring the juxtaposition of tradition and technology in the heart of Japan. From hidden shrines to neon-lit streets.',
      },
    ],
  },
  rsvp: {
    sectionId: 'rsvp',
    headingPrefix: 'Will You',
    headingEmphasis: 'Join Us?',
    deadline: 'Please RSVP by July 1st, 2026',
    nameLabel: 'Your Full Name',
    namePlaceholder: 'Enter your name',
    emailLabel: 'Email Address',
    emailPlaceholder: 'email@example.com',
    attendanceLabel: 'Attendance',
    attendance: {
      yes: { value: 'yes', label: 'Joyfully Attend' },
      no: { value: 'no', label: 'Regretfully Decline' },
    },
    guestsLabel: 'Total Guests',
    messageLabel: 'Dietary Requirements or Wishes',
    messagePlaceholder: 'Tell us anything we should know...',
    submitLabel: 'Confirm Attendance',
    successHeading: 'Thank You!',
    successMessage: "Your response has been received with love. We can't wait to celebrate this journey with you.",
    resetLabel: 'Send another response',
  },
  footer: {
    coupleLabel: 'Bjarty & Lisette',
    socialHref: '#',
    socialLabel: '#LisetteEnBjarty',
    contactHref: 'mailto:garciavanleeuwen@gmail.com',
    contactLabel: 'Contact Us',
    copyright: '© 2027 Lisette & Bjarty Wedding Journey',
    credit: 'Handcrafted with Love & Motion',
    links: [
      { id: 'privacy', label: 'Privacy', href: '#' },
      { id: 'registry', label: 'Registry', href: '#' },
    ],
  },
} satisfies SiteContent;
