import type { SiteContent } from '../types';

const event = {
  couple: {
    firstName: 'Lisette',
    secondName: 'Bjarty',
    displayName: 'Lisette & Bjarty',
    monogram: 'L & B',
  },
  date: {
    iso: '2027-05-22',
    display: '22 mei 2027',
  },
  timeZone: 'Europe/Amsterdam',
  place: 'Lage Vuursche',
  venue: {
    roomName: 'De Stal',
    organisationName: 'Restaurant De Lage Vuursche',
    address: 'Dorpsstraat 2, 3749 AD Lage Vuursche',
    mapsUrl: 'https://www.google.com/maps/place//data=!4m2!3m1!1s0x47c66a38fbf1566d:0x82db93feae7284e7?sa=X&ved=1t:8290&ictx=111',
  },
  rsvpDeadline: {
    iso: '2027-04-10',
    display: '10 april 2027',
  },
} satisfies SiteContent['event'];

const defineGiftContributions = (
  contributions: SiteContent['gifts']['contributions'],
) => contributions;

export const siteContent = {
  metadata: {
    language: 'nl',
    title: `${event.couple.displayName} | ${event.date.display}`,
  },
  event,
  contacts: {
    generalEmail: 'hallo@lisetteenbjarty.nl',
    rsvpEmail: 'rsvp@lisetteenbjarty.nl',
    giftsEmail: 'cadeau@lisetteenbjarty.nl',
  },
  navigation: {
    monogram: event.couple.monogram,
    items: [
      { id: 'schedule', label: 'Programma', href: '#schedule' },
      { id: 'dresscode', label: 'Dresscode', href: '#dresscode' },
      { id: 'location', label: 'Praktisch', href: '#location' },
      { id: 'cadeautips', label: 'Cadeautips', href: '#cadeautips' },
      { id: 'rsvp', label: 'RSVP', href: '#rsvp' },
    ],
    ctaLabel: 'RSVP',
    ctaHref: '#rsvp',
  },
  hero: {
    eyebrow: 'Wij gaan trouwen',
    firstName: event.couple.firstName,
    secondName: event.couple.secondName,
    dateLine: `${event.date.display} • ${event.place}`,
    scrollLabel: 'Ontdek onze dag',
  },
  story: {
    enabled: false,
    sectionId: 'story',
    heading: 'Ons verhaal',
    introduction: 'Binnenkort delen we hier meer over ons verhaal.',
    items: [],
    endingHeading: 'En het mooiste',
    endingText: 'moet nog komen.',
  },
  schedule: {
    sectionId: 'schedule',
    heading: 'Programma',
    dateLine: `Zaterdag ${event.date.display}`,
    events: [
      {
        id: 'ontvangst',
        time: '14.30 – 15.00',
        title: 'Ontvangst gasten',
        location: event.venue.roomName,
        icon: 'clock',
        description: 'We heten jullie van harte welkom bij De Stal.',
      },
      {
        id: 'ceremonie',
        time: '15.00 – 16.00',
        title: 'Ceremonie',
        location: event.venue.roomName,
        icon: 'heart',
        description: 'We geven elkaar het jawoord.',
      },
      {
        id: 'toost-en-taart',
        time: '16.00 – 17.00',
        title: 'Toost en taart',
        location: event.venue.roomName,
        icon: 'cake',
        description: 'Na de ceremonie proosten we samen en snijden we de taart aan.',
      },
      {
        id: 'diner',
        time: '17.00 – 20.00',
        title: 'Diner',
        location: event.venue.roomName,
        icon: 'utensils',
        description: 'We gaan met de daggasten aan tafel.',
      },
      {
        id: 'inloop-avondgasten',
        time: '20.00 – 20.30',
        title: 'Inloop avondgasten',
        location: event.venue.roomName,
        icon: 'users',
        description: 'We verwelkomen de avondgasten voor het feest.',
      },
      {
        id: 'feest',
        time: '20.30 – 00.00',
        title: 'Feest',
        location: event.venue.roomName,
        icon: 'music',
        description: 'We sluiten onze trouwdag samen af op de dansvloer.',
      },
    ],
  },
  dressCode: {
    sectionId: 'dresscode',
    eyebrow: 'Feestelijk & kleurrijk',
    heading: 'Dresscode',
    introduction: 'Kies een feestelijke outfit in blauw, turquoise, groen, geel, roze, paars, bruin, grijs, zwart, goud of zilver. Ga vooral voor een kleur waarin jij je mooi voelt.',
    inspirationLabel: 'Outfitinspiratie',
    inspiration: [
      {
        id: 'blauw',
        image: '/images/dresscode/blauw.webp',
        alt: 'Drie fictieve gasten in een marineblauw pak, een turquoise jurk en een hemelsblauw pak.',
      },
      {
        id: 'groen-geel-roze',
        image: '/images/dresscode/groen-geel-roze.webp',
        alt: 'Drie fictieve gasten in een smaragdgroen pak en jurken in geel en roze.',
      },
      {
        id: 'paars-bruin-grijs',
        image: '/images/dresscode/paars-bruin-grijs.webp',
        alt: 'Drie fictieve gasten in paarse en bruine pakken en een grijze jurk.',
      },
      {
        id: 'zwart-goud-zilver',
        image: '/images/dresscode/zwart-goud-zilver.webp',
        alt: 'Drie fictieve gasten in een zwart pak en jurken in goud en zilver.',
      },
    ],
    colorsLabel: 'Kleuren om uit te kiezen',
    colors: [
      { id: 'marineblauw', label: 'Marineblauw', color: '#1E3A5F', foreground: 'light' },
      { id: 'hemelsblauw', label: 'Hemelsblauw', color: '#5DADE2', foreground: 'dark' },
      { id: 'turquoise', label: 'Turquoise', color: '#0F766E', foreground: 'light' },
      { id: 'smaragdgroen', label: 'Smaragdgroen', color: '#047857', foreground: 'light' },
      { id: 'geel', label: 'Geel', color: '#EAB308', foreground: 'dark' },
      { id: 'roze', label: 'Roze', color: '#DB2777', foreground: 'light' },
      { id: 'paars', label: 'Paars', color: '#7E22CE', foreground: 'light' },
      { id: 'bruin', label: 'Bruin', color: '#7C4A2D', foreground: 'light' },
      { id: 'grijs', label: 'Grijs', color: '#6B7280', foreground: 'light' },
      { id: 'zwart', label: 'Zwart', color: '#1C1917', foreground: 'light' },
      { id: 'goud', label: 'Goud', color: '#CA8A04', foreground: 'dark' },
      { id: 'zilver', label: 'Zilver', color: '#CBD5E1', foreground: 'dark' },
    ],
    printNote: 'Een feestelijke print binnen dit kleurenpalet is ook van harte welkom.',
  },
  location: {
    sectionId: 'location',
    venueName: event.venue.roomName,
    venueContext: event.venue.organisationName,
    address: event.venue.address,
    mapHref: event.venue.mapsUrl,
    mapLabel: 'Open in Google Maps',
    heading: 'Praktische informatie',
    introduction: `Onze hele bruiloft vindt plaats bij ${event.venue.roomName} van ${event.venue.organisationName} in ${event.place}.`,
    travelOptions: [
      {
        id: 'auto',
        title: 'Met de auto',
        description: 'De locatie is het gemakkelijkst bereikbaar met de auto.',
        icon: 'car',
      },
      {
        id: 'parkeren',
        title: 'Gratis parkeren',
        description: 'Je kunt gratis parkeren op het parkeerterrein tegenover en achter het restaurant.',
        icon: 'parking',
      },
      {
        id: 'overnachten',
        title: 'Overnachten',
        description: 'Hotel Ernst Sillem Hoeve ligt iets verderop en is bereikbaar met de auto of taxi. Omdat het aantal kamers in de directe omgeving beperkt is, raden we aan om tijdig en rechtstreeks bij de accommodatie te reserveren.',
        icon: 'bed',
      },
      {
        id: 'terugreis',
        title: 'Veilig naar huis',
        description: 'Regel voor de terugreis bij voorkeur vooraf een taxi en rijd uiteraard niet met alcohol op.',
        icon: 'taxi',
      },
    ],
  },
  honeymoon: {
    enabled: false,
    sectionId: 'honeymoon',
    eyebrow: 'Onze reis',
    headingLineOne: 'Samen op',
    headingLineTwo: 'avontuur',
    quote: 'Binnenkort delen we hier meer over onze reis.',
    startDate: 'Meer informatie volgt',
    stops: [],
  },
  gifts: {
    enabled: true,
    sectionId: 'cadeautips',
    eyebrow: 'Cadeautips',
    heading: 'Geef ons een stukje van onze huwelijksreis',
    introduction: [
      'Twee dagen na onze bruiloft begint ons volgende avontuur: een reis van zes weken door China en Zuid-Korea. Van de Chinese Muur en sfeervolle bergdorpen tot tropische stranden, bruisende wereldsteden en Koreaanse spa’s.',
      'Het mooiste cadeau is natuurlijk dat jullie onze trouwdag met ons vieren. Willen jullie toch iets geven? Dan vinden we het heel bijzonder als jullie bijdragen aan een mooi moment tijdens onze huwelijksreis. Zo denken we onderweg steeds even aan jullie terug.',
    ],
    routeHeading: 'Onze route',
    travelDates: '24 mei – 5 juli 2027',
    route: [
      'Amsterdam',
      'Beijing',
      'Huangshan & Huizhou',
      'Wangxian Valley',
      'Hangzhou',
      'Shanghai & Suzhou',
      'Wenzhou',
      'Fuzhou & Pingtan',
      'Macau',
      'Hongkong',
      'Jeju',
      'Seoul',
      'Amsterdam',
    ],
    contributionsEyebrow: 'Een herinnering voor onderweg',
    contributionsHeading: 'Kies een moment om aan bij te dragen',
    contributions: defineGiftContributions([
      {
        id: 'chinese-muur',
        title: 'De Chinese Muur beklimmen',
        location: 'Beijing',
        description: 'Samen wandelen over een van de beroemdste bouwwerken ter wereld, met hopelijk een prachtig uitzicht over de bergen. Een onvergetelijke start van onze huwelijksreis.',
        ctaLabel: 'Draag bij aan de Chinese Muur',
      },
      {
        id: 'diner-beijing',
        title: 'Romantisch dineren in Beijing',
        location: 'Beijing',
        description: 'Na een dag tussen tempels, hutongs en keizerlijke paleizen sluiten we af met een bijzonder diner voor twee.',
        ctaLabel: 'Trakteer ons op een diner',
      },
      {
        id: 'zonsopkomst-huangshan',
        title: 'Zonsopkomst in de Gele Bergen',
        location: 'Huangshan',
        description: 'Vroeg uit bed om vanaf de bergtoppen de zon te zien opkomen boven de wolken. Een van de momenten waar we tijdens deze reis het meest naar uitkijken.',
        ctaLabel: 'Help ons de top te bereiken',
      },
      {
        id: 'lichtjes-wangxian-valley',
        title: 'Een avond tussen de lichtjes',
        location: 'Wangxian Valley',
        description: 'Wangxian Valley lijkt ’s avonds bijna een sprookje, met verlichte huisjes tegen de rotswanden, watervallen en kronkelende straatjes. Hier willen we samen rustig ronddwalen en ergens iets lekkers eten.',
        ctaLabel: 'Geef ons een sprookjesavond',
      },
      {
        id: 'west-lake',
        title: 'Varen en ontspannen aan West Lake',
        location: 'Hangzhou',
        description: 'Een rustige boottocht over West Lake, gevolgd door een middag in de spa. Precies het soort ontspannen dag dat tijdens een lange huwelijksreis niet mag ontbreken.',
        ctaLabel: 'Draag bij aan onze relaxdag',
      },
      {
        id: 'tuinen-suzhou',
        title: 'Samen verdwalen in de tuinen van Suzhou',
        location: 'Suzhou',
        description: 'Een dag tussen klassieke Chinese tuinen, oude bruggetjes en smalle kanalen. Met onderweg natuurlijk tijd voor thee en lokale hapjes.',
        ctaLabel: 'Geef ons een dagje Suzhou',
      },
      {
        id: 'skyline-shanghai',
        title: 'Dineren met uitzicht op de skyline',
        location: 'Shanghai',
        description: 'Shanghai beleven vanaf grote hoogte, terwijl de lichtjes van de stad en de Bund onder ons verschijnen. Een romantische avond in een van de grootste steden ter wereld.',
        ctaLabel: 'Trakteer ons in Shanghai',
      },
      {
        id: 'lokaal-wenzhou',
        title: 'Proeven van het lokale leven',
        location: 'Wenzhou',
        description: 'In Wenzhou willen we even van de bekende toeristische route af: oude straten ontdekken, lokale gerechten proberen en samen ervaren hoe het dagelijks leven hier voelt.',
        ctaLabel: 'Geef ons een dag in Wenzhou',
      },
      {
        id: 'strand-pingtan',
        title: 'Een stranddag op Pingtan',
        location: 'Fuzhou & Pingtan',
        description: 'Na alle steden en treinreizen is het tijd voor zee. We willen langs de kust van Pingtan rijden, uitwaaien op het strand en de dag afsluiten met verse vis en uitzicht op het water.',
        ctaLabel: 'Draag bij aan onze stranddag',
      },
      {
        id: 'casino-macau',
        title: 'Een gokje wagen in Macau',
        location: 'Macau',
        description: 'Tijdens onze drie nachten in Macau mag één echte casinoavond natuurlijk niet ontbreken. Bjarty wil graag een nacht pokeren, terwijl we samen genieten van alle lichtjes, luxe en entertainment.',
        ctaLabel: 'Geef Bjarty een pokerchip',
      },
      {
        id: 'zwembad-macau',
        title: 'Bijkomen aan het zwembad',
        location: 'Macau',
        description: 'Na onze casinoavond plannen we bewust een rustige dag: uitslapen, ontspannen aan het zwembad en misschien samen naar de spa.',
        ctaLabel: 'Trakteer ons op een relaxdag',
      },
      {
        id: 'zee-hongkong',
        title: 'Dim sum en een dag aan zee',
        location: 'Hongkong',
        description: 'Hongkong heeft niet alleen wolkenkrabbers en drukke markten, maar ook verrassend mooie stranden. We combineren een ontspannen stranddag met dim sum en uitzicht over Victoria Harbour.',
        ctaLabel: 'Geef ons een dag Hongkong',
      },
      {
        id: 'auto-jeju',
        title: 'Jeju ontdekken met de auto',
        location: 'Jeju',
        description: 'Op Jeju willen we langs vulkanische landschappen, watervallen en kleine kustdorpjes rijden. Onderweg stoppen we voor mooie uitzichten, lokale specialiteiten en alles wat spontaan op ons pad komt.',
        ctaLabel: 'Draag bij aan ons Jeju-avontuur',
      },
      {
        id: 'strand-spa-jeju',
        title: 'Een vrije dag voor strand en spa',
        location: 'Jeju',
        description: 'Van onze vijf nachten op Jeju reserveren we ook een dag om helemaal niets te hoeven: rustig ontbijten, zwemmen, naar het strand en misschien samen naar de spa.',
        ctaLabel: 'Geef ons een dag helemaal niets',
      },
      {
        id: 'spa-seoul',
        title: 'Samen naar een Koreaanse spa',
        location: 'Seoul',
        description: 'Aan het einde van onze reis willen we ontspannen in een echte Koreaanse jjimjilbang. Even bijkomen van alle indrukken voordat we weer naar huis vliegen.',
        ctaLabel: 'Stuur ons naar de spa',
      },
      {
        id: 'laatste-avond-seoul',
        title: 'Onze laatste avond in Seoul',
        location: 'Seoul',
        description: 'Onze huwelijksreis afsluiten met een bijzonder diner, een wandeling door de verlichte stad en samen terugkijken op zes onvergetelijke weken.',
        ctaLabel: 'Trakteer ons op de laatste avond',
      },
    ]),
    // Payment URLs become public in the site bundle; add only reviewed, reusable links.
    paymentLinksEnabled: false,
    paymentProvider: null,
    paymentUnavailableLabel: 'Bijdragen wordt binnenkort mogelijk.',
    externalPaymentNote: 'Je betaalt via een externe betaalprovider. Die partij verwerkt de gegevens die nodig zijn om de betaling uit te voeren.',
    thanksHeading: 'Bedankt dat jullie met ons meereizen',
    thanksText: [
      'Welke bestemming of ervaring jullie ook kiezen: iedere bijdrage wordt onderdeel van onze huwelijksreis. We zullen onderweg foto’s maken en aan jullie denken wanneer we het gekozen moment beleven.',
      'Dank jullie wel dat jullie helpen om van onze eerste reis als getrouwd stel iets onvergetelijks te maken.',
    ],
    signature: event.couple.displayName,
  },
  rsvp: {
    sectionId: 'rsvp',
    headingPrefix: 'Ben je',
    headingEmphasis: 'erbij?',
    deadline: `Laat ons uiterlijk ${event.rsvpDeadline.display} weten of je erbij bent.`,
    statusHeading: 'RSVP opent binnenkort',
    statusMessage: 'We werken aan een veilig formulier waarmee je reactie direct wordt opgeslagen. Zodra het klaar is, kun je hier reageren.',
    contactLabel: 'Vraag over RSVP',
    codeEntry: {
      eyebrow: 'Persoonlijke uitnodiging',
      heading: 'Vul jullie huishoudcode in',
      introduction: 'De code staat onder de QR op jullie uitnodiging. We gebruiken hem om alleen de juiste namen en RSVP-vragen te tonen.',
      label: 'Huishoudcode',
      helper: 'Spaties, hoofdletters en koppeltekens maken niet uit.',
      invalidFormat: 'Deze code kunnen we niet gebruiken. Controleer de uitnodiging en probeer het opnieuw.',
      submitLabel: 'Code controleren',
      switchLabel: 'Andere code proberen',
    },
    form: {
      invitationHeading: 'Deze uitnodiging is voor',
      dayVariantLabel: 'Uitgenodigd voor de hele dag',
      dayArrivalMessage: 'Jullie zijn welkom vanaf 14.30 uur.',
      eveningVariantLabel: 'Uitgenodigd voor het avondfeest',
      eveningArrivalMessage: 'Jullie zijn welkom vanaf 20.00 uur.',
      wrongNamesMessage: 'Kloppen de namen niet? Mail ons dan even.',
      attendanceQuestionPrefix: 'Is',
      attendanceYesLabel: 'Ja, gezellig',
      attendanceNoLabel: 'Nee, helaas',
      mealQuestionPrefix: 'Kies een maaltijd voor',
      mealChoices: {
        fish: 'Vis',
        meat: 'Vlees',
        vegetarian: 'Vega',
        vegan: 'Vegan',
      },
      emailLabel: 'E-mailadres (optioneel)',
      emailHelper: 'Als je je e-mailadres invult, kunnen we je via dit adres op de hoogte houden van praktische informatie over de bruiloft.',
      emailConfirmationEnabledNote: `Na het opslaan sturen we het bevestigingsnummer ook automatisch naar dit adres. Met dezelfde huishoudcode of persoonlijke uitnodigingslink kun je je reactie tot en met ${event.rsvpDeadline.display} aanpassen.`,
      emailConfirmationDisabledNote: `Je ontvangt nog geen automatische bevestigingsmail; bewaar na het opslaan je bevestigingsnummer. Met dezelfde huishoudcode of persoonlijke uitnodigingslink kun je je reactie tot en met ${event.rsvpDeadline.display} aanpassen.`,
      emailConfirmationDemoNote: 'Dit is een lokale demonstratie. Er wordt geen e-mail verstuurd en je testreactie blijft alleen tijdelijk in dit tabblad staan.',
      messageLabel: 'Bericht voor ons (optioneel)',
      messageHelper: 'Wil je nog iets aan ons kwijt? Deel hier alleen informatie die nodig is voor onze bruiloft.',
      submitLabel: 'Reactie versturen',
      updateLabel: 'Wijzigingen opslaan',
      privacyHeading: 'Wat we met je gegevens doen',
      privacyMessage: 'We gebruiken je naam, aanwezigheid, maaltijdkeuze, e-mailadres en een eventueel bericht alleen om onze bruiloft te organiseren. Voor de automatische bevestigingsmail delen we uit je RSVP alleen je e-mailadres en bevestigingsnummer met onze maildienst. Aanwezigheid, maaltijdkeuzes en je vrije bericht worden niet meegestuurd. De maildienst verwerkt daarnaast noodzakelijke verzendmetadata, het onderwerp en de inhoud van de bevestigingsmail. Je volledige RSVP kan alleen worden bekeken door Lisette, Bjarty en de mensen die onze RSVP beheren. We verwijderen de RSVP-gegevens uiterlijk 1 augustus 2027. Heb je een vraag over je gegevens of wil je ze inzien of corrigeren? Mail rsvp@lisetteenbjarty.nl.',
      privacyEmailDisabledMessage: 'We gebruiken je naam, aanwezigheid, maaltijdkeuze, e-mailadres en een eventueel bericht alleen om onze bruiloft te organiseren. Er wordt nog geen automatische bevestigingsmail verstuurd en je RSVP-gegevens worden daarom niet met een maildienst gedeeld. Je volledige RSVP kan alleen worden bekeken door Lisette, Bjarty en de mensen die onze RSVP beheren. We verwijderen de RSVP-gegevens uiterlijk 1 augustus 2027. Heb je een vraag over je gegevens of wil je ze inzien of corrigeren? Mail rsvp@lisetteenbjarty.nl.',
      demoPrivacyMessage: 'In deze lokale demonstratie wordt je testdata alleen tijdelijk in dit tabblad bewaard. De testdata wordt niet naar Google Sheets of een maildienst gestuurd en er wordt geen e-mail verstuurd.',
    },
    states: {
      loading: 'We halen jullie uitnodiging op…',
      invalidLink: 'Deze persoonlijke link is niet geldig of niet meer actief. Controleer of je de volledige link hebt geopend.',
      invalidCode: 'Deze huishoudcode is niet geldig of niet meer actief. Controleer de code op jullie uitnodiging.',
      loadError: 'We kunnen je uitnodiging nu niet ophalen. Probeer het opnieuw; er is niets gewijzigd.',
      offline: 'Je bent offline. Je invoer blijft op dit scherm staan. Maak opnieuw verbinding en probeer het daarna opnieuw.',
      submitting: 'Je reactie wordt veilig opgeslagen…',
      validationError: 'Controleer de gemarkeerde antwoorden.',
      submitError: 'Opslaan is niet gelukt. Je invoer staat nog klaar. Probeer het opnieuw.',
      conflict: 'Er is voor deze uitnodiging intussen een nieuwere reactie opgeslagen. Laad eerst die reactie en voer je wijziging daarna opnieuw in; zo overschrijven we niets ongemerkt.',
      rateLimited: 'Er zijn te veel pogingen gedaan. Wacht even en probeer het daarna opnieuw. Je invoer blijft staan.',
      closed: 'De RSVP is gesloten. Wil je nog iets wijzigen? Mail rsvp@lisetteenbjarty.nl.',
      success: 'Je reactie is opgeslagen.',
      receiptLabel: 'Bevestigingsnummer',
      receiptAccessHelper: `Gebruik dezelfde huishoudcode of persoonlijke uitnodigingslink om je reactie tot en met ${event.rsvpDeadline.display} aan te passen.`,
      receiptEmailEnabledHelper: 'We sturen ditzelfde bevestigingsnummer ook naar het hierboven ingevulde e-mailadres.',
      receiptEmailEmptyHelper: 'Zonder e-mailadres sturen we geen bevestigingsmail.',
      receiptEmailDisabledHelper: 'Er wordt nog geen automatische bevestigingsmail verstuurd; bewaar dit bevestigingsnummer daarom zelf.',
      demoReceiptHelper: 'Dit bevestigingsnummer is alleen onderdeel van de lokale demonstratie. Er wordt geen e-mail verstuurd. Gebruik de demo-huishoudcode om je testreactie opnieuw te openen.',
      retryLabel: 'Opnieuw proberen',
      loadLatestLabel: 'Laatste opgeslagen reactie bekijken',
    },
  },
  footer: {
    coupleLabel: event.couple.displayName,
    contactLabel: 'Contact',
    copyright: `© 2027 ${event.couple.displayName}`,
    credit: 'Met liefde gemaakt',
    links: [],
  },
} satisfies SiteContent;
